#pragma once

#pragma region SIMON
#define SIMON_WALKING_SPEED		0.1f 
//0.1f
#define SIMON_JUMP_SPEED_Y		0.5f
#define SIMON_JUMP_DEFLECT_SPEED 0.2f
#define SIMON_GRAVITY			0.002f
#define SIMON_DIE_DEFLECT_SPEED	 0.5f

#define SIMON_STATE_IDLE_LEFT			0
#define SIMON_STATE_WALKING_LEFT		1
#define SIMON_STATE_WALKING_RIGHT		2
#define SIMON_STATE_SIT					3
#define SIMON_STATE_JUMP				4
#define SIMON_STATE_DIE					5
#define SIMON_STATE_HIT_STAND			6
#define SIMON_STATE_HIT_SIT				7
#define SIMON_STATE_IDLE_RIGHT			8
#define SIMON_STATE_SIT_RIGHT			9
#define SIMON_STATE_JUMP_RIGHT			10
#define SIMON_STATE_DIE_RIGHT			11
#define SIMON_STATE_HIT_STAND_RIGHT		12
#define SIMON_STATE_HIT_SIT_RIGHT		13
#define SIMON_STATE_GET_ITEM_LEFT		14
#define SIMON_STATE_GET_ITEM_RIGHT		15
#define SIMON_GO_UPSTAIR_RIGHT			16
#define SIMON_GO_UPSTAIR_LEFT			17
#define SIMON_HIT_UPSTAIR_RIGHT			18
#define SIMON_HIT_UPSTAIR_LEFT			19
#define SIMON_GO_DOWNSTAIR_RIGHT		20
#define SIMON_GO_DOWNSTAIR_LEFT			21
#define SIMON_HIT_DOWNSTAIR_RIGHT		22
#define SIMON_HIT_DOWNSTAIR_LEFT		23
#define SIMON_STAND_ON_UPSTAIR_RIGHT	24
#define SIMON_STAND_ON_UPSTAIR_LEFT		25
#define SIMON_STAND_ON_DOWNSTAIR_RIGHT	26
#define SIMON_STAND_ON_DOWNSTAIR_LEFT	27
#define SIMON_STATE_INJURED_RIGHT		28
#define SIMON_STATE_INJURED_LEFT		29

//#define SIMON_ANI_IDLE_RIGHT		0
//#define SIMON_ANI_WALKING_RIGHT		1
//#define SIMON_ANI_SIT_RIGHT			2
//#define SIMON_ANI_JUMP_RIGHT		3
//#define SIMON_ANI_DIE_RIGHT			4
//#define SIMON_ANI_IDLE_LEFT			5
//#define SIMON_ANI_WALKING_LEFT		6
//#define SIMON_ANI_SIT_RIGHT			7
//#define SIMON_ANI_JUMP_RIGHT		8
//#define SIMON_ANI_DIE_RIGHT			9

#define SIMON_BBOX_WIDTH  48
#define SIMON_BBOX_HEIGHT 60

#define SIMON_UNTOUCHABLE_TIME 1000
#pragma endregion

#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"04 - Collision"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 480

#define MAX_FRAME_RATE 120

#define ID_TEX_SIMON 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20